/**
 * GENERATED by `npm run plates` -- do not edit by hand.
 *
 * To use real photography instead, drop files into /public/plates and point
 * `avif`/`webp` at them; nothing downstream depends on how they were made.
 */

export type PlateId =
  | "atrium"
  | "veil"
  | "flacon"
  | "colonnade"
  | "monolith"
  | "stair"
  | "sphere"
  | "aperture"
  | "horizon"
  | "vessel"
  | "fold"
  | "bottle-mineral"
  | "bottle-musk"
  | "bottle-woods";

export interface Plate {
  id: PlateId;
  label: string;
  width: number;
  height: number;
  avif: string;
  webp: string;
  /** Inlined 24px blur-up, shown until the full file decodes. */
  blur: string;
}

export const PLATES: Record<PlateId, Plate> = {
  "atrium": {
    id: "atrium",
    label: "Atrium, morning",
    width: 1280,
    height: 1600,
    avif: "/plates/atrium.avif",
    webp: "/plates/atrium.webp",
    blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBQCdASoYAB4APuFio00opiMiMAwBEBwJZwDM0Bu1O3OdrAnzPZF5WAHs1XszrmPqwsAA/vQyvfpaEOmCLLPNKoxJU/D1Io82jlNvYX0y3b40naMtV5OxasUYmC3cEYLgIV67yoESwSRAIsQz4Oy5aRIdnAAA",
  },
  "veil": {
    id: "veil",
    label: "Veil study",
    width: 1280,
    height: 1600,
    avif: "/plates/veil.avif",
    webp: "/plates/veil.webp",
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQBQCdASoYAB4APulkqU4pJaQiMAgBIB0JaQDOdCHgV7JhPB1AVHF9GX0RRX7kNx8xRTgA/tJcuI9AyIiUOw6GOOqEwyiqK8jVjjob8sU2T03ny3/LGehfi5UWQEabqFtBxwBgd+V8WGu2z4JkAAAA",
  },
  "flacon": {
    id: "flacon",
    label: "Flacon no. 1",
    width: 1280,
    height: 1600,
    avif: "/plates/flacon.avif",
    webp: "/plates/flacon.webp",
    blur: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBQCdASoYAB4APulmqk2pJaQiMAgBIB0JaQAKusy/hi7tf7ton1XaP27BvNN1OK/FtGnAQAD9nKEf/vGLtXcpcKpslmv/S7Qu4CrEogjPjwh+UkyD5swYiGXQj/lzIDHgKSH6cGRO85QFxV8ppizI5Oqt7KEeIROV6V9qhVQAV6bS4b9U3tsndfrYJZ3mDL5mLSVDfhtCMpwmjgAAAA==",
  },
  "colonnade": {
    id: "colonnade",
    label: "Colonnade",
    width: 1760,
    height: 990,
    avif: "/plates/colonnade.avif",
    webp: "/plates/colonnade.webp",
    blur: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoYAA4ALq10ul0jKSkpCQCsSzgABUPrDVze7ljOus0AAP7x9qMnZwVtxiV+7quHNZT9F4vfc1z6j+2XQ/XGWEAA",
  },
  "monolith": {
    id: "monolith",
    label: "Monolith",
    width: 1680,
    height: 1120,
    avif: "/plates/monolith.avif",
    webp: "/plates/monolith.webp",
    blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoYABAAPulmq00pJiQiMAgBIB0JaQAAWp/jmwuSp9Am1VAA/ucfhkrLUGmXuQW5mZj7dxko1DkGhQE+QrRFccD2GbgAAA==",
  },
  "stair": {
    id: "stair",
    label: "Ascent",
    width: 1280,
    height: 1600,
    avif: "/plates/stair.avif",
    webp: "/plates/stair.webp",
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBQCdASoYAB4APulgq06pJSQiMBgIASAdCWcAABz6Pt2swr/Je/pdP5NAMWfzmP4AAPrUD8Q6wPtpRoYaFG3q7FXeysQ6wC6v6a0ZzX712sVSQ3xGJUtgWV5ZRTAm4DDvZPOIueimf4O0OAA=",
  },
  "sphere": {
    id: "sphere",
    label: "Form study",
    width: 1360,
    height: 1360,
    avif: "/plates/sphere.avif",
    webp: "/plates/sphere.webp",
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASoYABgAPulsrlEpJiQiqAgBIB0JaQAAHFWwju6nzvTrfGbtOuAi2OE+AAD9zaav2HNY3pKsfW4u7anfXiP9YTixjoo7U0IJd1YHABYzwmuudLBpHFiqXHA5DjYIeiT+0/i/AAAA",
  },
  "aperture": {
    id: "aperture",
    label: "Aperture",
    width: 1200,
    height: 1600,
    avif: "/plates/aperture.avif",
    webp: "/plates/aperture.webp",
    blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBQCdASoYACAAPulgqU6pJSOiMBgIASAdCWkAAIbCcUk5chnUeUpvZq4f+hHSO0glwAD+72HSwp5gt15oEfpkGRAwHQ/eUJH0JP3ouIfGfcgI+sipjdBYCxQZFsG2EmA+8Ss3coU46ghWR6ruQh7r8AMwesAA",
  },
  "horizon": {
    id: "horizon",
    label: "Cove",
    width: 1760,
    height: 990,
    avif: "/plates/horizon.avif",
    webp: "/plates/horizon.webp",
    blur: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABwAwCdASoYAA4ALq10ul0jKSkpCQCsS0gABc6/OnqDJf/9kiAA/vfn9qMVLZvknqOzUlMsk5cQKqlP0X3F4HLG5u6AAA==",
  },
  "vessel": {
    id: "vessel",
    label: "Vessel",
    width: 1280,
    height: 1600,
    avif: "/plates/vessel.avif",
    webp: "/plates/vessel.webp",
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABwBACdASoYAB4APulqsFApJiUjKAqpIB0JaQABNuBYU1LZGHpAOr6apL3kAAD+8BCChUnzbFMwNc9+5DYrhxVjpFs5Q8QRgNaIjgkHPZYbWvc65j9ZaD/HygoAAA==",
  },
  "fold": {
    id: "fold",
    label: "Fold",
    width: 1200,
    height: 1600,
    avif: "/plates/fold.avif",
    webp: "/plates/fold.webp",
    blur: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoYACAAPtlWpU0oJKOiN/qoAQAbCWkAAFvj2/sfJz55DlK5SHyKER/Zh0lGEw8AAP70LhtyxL5QauhKnBpMTox/0lgEud744hPvO+Oy8m8T5iBJxsy1ClTg3+Kn9+GkU9oQXVi2VW5Qpbm1nk+pT80jh3rdp9u3jDWfVAEiwqUEgAAA",
  },
  "bottle-mineral": {
    id: "bottle-mineral",
    label: "Atrium — the flacon",
    width: 1280,
    height: 1600,
    avif: "/plates/bottle-mineral.avif",
    webp: "/plates/bottle-mineral.webp",
    blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABwBACdASoYAB4APtVWok0oJKMiN/qoAQAaiWkAAP2LFRV8dTVjSUhiVzVueAD+8I3EFR4cSY+YP/vPUgsTtn7XXssewH87ejjZnv1tCRX6LZtSDxkAAA==",
  },
  "bottle-musk": {
    id: "bottle-musk",
    label: "Veil — the flacon",
    width: 1280,
    height: 1600,
    avif: "/plates/bottle-musk.avif",
    webp: "/plates/bottle-musk.webp",
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBQCdASoYAB4APulcpk4pJKMiMBgMASAdCWcAuwARBVqi59Poul0CaT5IXOuA6R1KiAD9MBS4Dt9/xicFXuLetTbAj6+73JPKdnhTX8/PrjXJ1ZfK9tWdg8/QtXHa3cPHC9MAAAA=",
  },
  "bottle-woods": {
    id: "bottle-woods",
    label: "Monolith — the flacon",
    width: 1280,
    height: 1600,
    avif: "/plates/bottle-woods.avif",
    webp: "/plates/bottle-woods.webp",
    blur: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAwCdASoYAB4APt1apE0opSOiMAwBEBuJaQAAW+s3eqd7j0IYAAD+9oZHZuiUlY5XvKtODSF0MGoAAAA=",
  },
};

export const plate = (id: PlateId): Plate => PLATES[id];
